<?php

return [
    'auth' => [
        'failed' => [
            'code' => 'AUTH-001',
            'userInfo' => 'No se pudo iniciar sesión.',
            'supportInfo' => 'El intento de autenticación fallo por credenciales invalidas, usuario inexistente, cuenta bloqueada o estado no permitido.',
            'developerInfo' => 'AuthService::login regreso credentials_valid=false. Revisar búsqueda de username normalizado, resultado de Hash::check, estado del usuario, locked_until y evento de auditoria login.failed. No exponer cual condición fallo.',
        ],
        'additional_verification' => [
            'code' => 'AUTH-002',
            'userInfo' => 'Verificación adicional requerida.',
            'supportInfo' => 'La password fue aceptada, pero el rol requiere completar MFA antes de crear una sesión autenticada.',
            'developerInfo' => 'Se creo sesión MFA pendiente con auth_pending_user_id/auth_pending_level/auth_pending_started_at. El usuario debe completar TOTP y, si aplica, WebAuthn según role.required_mfa_level.',
        ],
        'session_expired' => [
            'code' => 'AUTH-003',
            'userInfo' => 'La sesión expiró. Intenta de nuevo.',
            'supportInfo' => 'La sesión normal, MFA pendiente o sesión admin supero la ventana permitida.',
            'developerInfo' => 'ExpireMfaPendingSession o AdminSessionTimeout limpiaron el estado de sesión. Revisar auth_pending_started_at, admin_last_activity_at, ventanas de expiración configuradas y security_audit_logs.event=session.expired.',
        ],
        'logout_completed' => [
            'code' => 'AUTH-004',
            'userInfo' => 'Sesión cerrada.',
            'supportInfo' => 'Logout completado con invalidacion de sesión actual.',
            'developerInfo' => 'LogoutController ejecuto Auth::logout, limpio llaves de sesión MFA/admin, inválido la sesión y regenero el token CSRF. Debe existir evento de auditoria logout.success.',
        ],
        'register_failed' => [
            'code' => 'AUTH-005',
            'userInfo' => 'No se pudo completar el registro.',
            'supportInfo' => 'El registro fallo después de validacion por una condición interna o conflicto no exponible.',
            'developerInfo' => 'RegisterController capturo Throwable desde AuthService::register. Revisar resultado de validacion, restricciones unique de username/email, creacion de rol por defecto y errores de transacción DB.',
        ],
        'token_invalid' => [
            'code' => 'AUTH-006',
            'userInfo' => 'El enlace no es válido.',
            'supportInfo' => 'El token de recuperación no existe, no coincide con el hash guardado o no pertenece al correo enviado.',
            'developerInfo' => 'PasswordResetService::reset no pudo coincidir el hash del token. Revisar fila password_reset_tokens, token_hash/datos del broker de password, normalizacion de email y enlace user_id.',
        ],
        'token_expired' => [
            'code' => 'AUTH-007',
            'userInfo' => 'El enlace expiró.',
            'supportInfo' => 'El token de recuperación existe pero está fuera de la ventana de expiración configurada.',
            'developerInfo' => 'El token de reset supero expires_at o created_at + auth.passwords.users.expire. El evento de auditoria token.expired debe incluir user_id cuando exista.',
        ],
        'password_changed' => [
            'code' => 'AUTH-008',
            'userInfo' => 'Contraseña actualizada.',
            'supportInfo' => 'La password fue cambiada y se revocaron otras sesiones.',
            'developerInfo' => 'ProfileController::updatePassword actualizo hash de password, password_changed_at y remember_token; luego UserSessionService elimino otras sesiones y regenero la sesión actual.',
        ],
        'login_completed' => [
            'code' => 'AUTH-009',
            'userInfo' => 'Sesión iniciada.',
            'supportInfo' => 'Login completado para el nivel MFA requerido.',
            'developerInfo' => 'Flujo de autenticación completado. Revisar auth_completed_mfa_level, last_login_at, metadata de auditoria login.success y redirección según rol.',
        ],
        'account_locked' => [
            'code' => 'AUTH-010',
            'userInfo' => 'No se pudo iniciar sesión.',
            'supportInfo' => 'La cuenta está bloqueada o no cumple el estado requerido para iniciar sesión.',
            'developerInfo' => 'El status/locked_until del usuario impidio el login. Mantener userInfo genérico para no revelar el estado de la cuenta.',
        ],
    ],
    'mfa' => [
        'invalid_totp' => [
            'code' => 'MFA-001',
            'userInfo' => 'No se pudo verificar el código.',
            'supportInfo' => 'El código TOTP no coincide, ya fue usado o no está dentro de la ventana permitida.',
            'developerInfo' => 'TotpService::verify regreso null. Revisar digits/period/window configurados, user.totp_secret cifrado, protección replay en user.totp_last_used_counter y desfase de reloj del servidor.',
        ],
        'totp_expired' => [
            'code' => 'MFA-002',
            'userInfo' => 'La verificación TOTP expiró.',
            'supportInfo' => 'El setup o actualizacion de TOTP supero la ventana temporal permitida.',
            'developerInfo' => 'totp_setup_started_at es anterior a la ventana permitida o falta totp_setup_secret en sesión. Las llaves de sesión se limpiaron antes de regresar el error.',
        ],
        'totp_update_required_verification' => [
            'code' => 'MFA-003',
            'userInfo' => 'Contraseña actual o código TOTP actual incorrectos.',
            'supportInfo' => 'La verificación para reemplazar TOTP fallo por password actual o código TOTP actual inválidos.',
            'developerInfo' => 'La actualizacion TOTP fallo porque Hash::check(current_password) fue false o TotpService::verify(current_otp, secreto existente, ultimo contador) regreso null. Auditoria reason=update_verification_failed.',
        ],
        'totp_updated' => [
            'code' => 'MFA-004',
            'userInfo' => 'TOTP actualizado correctamente.',
            'supportInfo' => 'Se reemplazo el secreto TOTP y se regeneraron recovery codes.',
            'developerInfo' => 'TotpService::enableForUser reemplazo totp_secret cifrado, reinicio totp_last_used_counter, actualizo totp_enabled_at y reemplazo recovery_codes dentro de una transacción.',
        ],
        'recovery_code_invalid' => [
            'code' => 'MFA-005',
            'userInfo' => 'No se pudo verificar el código.',
            'supportInfo' => 'Código de recuperación inválido, ya usado o no asociado al usuario.',
            'developerInfo' => 'RecoveryCodeLoginController::consumeCode no encontro una fila recovery_codes sin usar cuyo hash coincida con el código normalizado enviado. Evento de auditoria recovery_code.failed.',
        ],
        'mfa_pending_missing' => [
            'code' => 'MFA-006',
            'userInfo' => 'Verificación no disponible. Inicia sesión de nuevo.',
            'supportInfo' => 'No existe sesión MFA pendiente para completar este paso.',
            'developerInfo' => 'MfaPendingSessionService::pendingUser regreso null o falta auth_pending_user_id. La ruta se alcanzo fuera del flujo esperado posterior a password.',
        ],
        'insufficient_mfa_level' => [
            'code' => 'MFA-007',
            'userInfo' => 'Verificación adicional requerida.',
            'supportInfo' => 'El nivel MFA completado no alcanza el requerido por la ruta.',
            'developerInfo' => 'EnsureMfaLevel rechazo la solicitud porque auth_completed_mfa_level < parámetro mfa.level de la ruta. Revisar valor de sesión, role.required_mfa_level y orden de middlewares.',
        ],
        'totp_reused' => [
            'code' => 'MFA-008',
            'userInfo' => 'Ese código TOTP ya fue usado. Espera el siguiente código.',
            'supportInfo' => 'El código coincide con una ventana TOTP valida, pero su contador ya fue usado y se bloqueo por protección anti-replay.',
            'developerInfo' => 'TotpService::verify sin lastUsedCounter encontro coincidencia, pero el contador resultante fue <= user.totp_last_used_counter. Pedir al usuario esperar el siguiente periodo TOTP.',
        ],
    ],
    'passkey' => [
        'validation_failed' => [
            'code' => 'PASSKEY-001',
            'userInfo' => 'No se pudo validar la Passkey.',
            'supportInfo' => 'El registro o autenticación WebAuthn fallo por challenge, origin, RP ID, firma, credencial o user verification.',
            'developerInfo' => 'WebauthnService lanzo excepción durante processCreate/processGet. Revisar clase sanitizada del fallo, config rp_id/origin, credential_id_hash guardado, public_key, sign_count, llaves challenge de sesión y mensaje lbuchs WebAuthnException solo en logs seguros.',
        ],
        'challenge_expired' => [
            'code' => 'PASSKEY-002',
            'userInfo' => 'La verificación de Passkey expiró.',
            'supportInfo' => 'El challenge WebAuthn no existe o expiró antes de completar la operacion.',
            'developerInfo' => 'Falta webauthn_register_challenge/webauthn_login_challenge o *_challenge_at, ya fue consumido, o es anterior a config(webauthn.timeout). Se requiere solicitar opciones nuevas.',
        ],
        'required' => [
            'code' => 'PASSKEY-003',
            'userInfo' => 'Debe quedar al menos una Passkey activa.',
            'supportInfo' => 'La cuenta requiere Passkey y no se permite borrar la ultima credencial valida.',
            'developerInfo' => 'El borrado de WebauthnCredential fue bloqueado porque user->webauthnCredentials()->count() <= 1 mientras webauthn_enabled_at indica que Passkeys están activas/requeridas.',
        ],
        'added' => [
            'code' => 'PASSKEY-004',
            'userInfo' => 'Passkey agregada correctamente.',
            'supportInfo' => 'Credencial WebAuthn registrada y asociada al usuario.',
            'developerInfo' => 'Fila WebauthnCredential creada con credential_id_hash único, credential_id cifrado, public_key, transports y sign_count inicial. Evento de auditoria webauthn.registered.',
        ],
        'removed' => [
            'code' => 'PASSKEY-005',
            'userInfo' => 'Passkey eliminada correctamente.',
            'supportInfo' => 'Credencial WebAuthn eliminada sin dejar la cuenta sin Passkey.',
            'developerInfo' => 'Borrado de WebauthnCredential completado tras validar propietario y conteo. Evento de auditoria webauthn.deleted/passkey.deleted debe incluir user_id y actor_id opcional.',
        ],
        'https_required' => [
            'code' => 'PASSKEY-006',
            'userInfo' => 'Passkeys requiere HTTPS.',
            'supportInfo' => 'El navegador no permite WebAuthn fuera de contexto seguro.',
            'developerInfo' => 'window.isSecureContext=false antes de navigator.credentials.create/get. Usar HTTPS, localhost o un tunel válido cuyo origin coincida con config(webauthn.origin).',
        ],
        'browser_unsupported' => [
            'code' => 'PASSKEY-007',
            'userInfo' => 'Passkeys no está disponible en este navegador.',
            'supportInfo' => 'El navegador o WebView no expone PublicKeyCredential/navigator.credentials.',
            'developerInfo' => 'Falta window.PublicKeyCredential o navigator.credentials. Causa comun: navegadores embebidos de mensajeria/email/camara o plataforma no soportada.',
        ],
        'options_failed' => [
            'code' => 'PASSKEY-008',
            'userInfo' => 'No se pudo preparar la Passkey.',
            'supportInfo' => 'Fallo la generacion de opciones WebAuthn en el servidor.',
            'developerInfo' => 'El endpoint de opciones register/login regreso non-2xx o JSON inválido. Revisar resolución de usuario pendiente/autenticado, config RP, lista de credenciales y rate limiting.',
        ],
        'cancelled_or_expired' => [
            'code' => 'PASSKEY-009',
            'userInfo' => 'Operacion cancelada o expirada.',
            'supportInfo' => 'El usuario cancelo la operacion WebAuthn o el navegador agoto el tiempo.',
            'developerInfo' => 'El navegador lanzo NotAllowedError durante navigator.credentials.create/get. Puede ser cancelacion del usuario, timeout, autenticador no disponible o conditional UI bloqueada.',
        ],
        'credential_not_found' => [
            'code' => 'PASSKEY-010',
            'userInfo' => 'No se pudo validar la Passkey.',
            'supportInfo' => 'La credencial enviada no pertenece al usuario o no existe.',
            'developerInfo' => 'La búsqueda por credential_id_hash regreso null o credential.user_id no coincide con el usuario pendiente/autenticado. No revelar existencia de credencial al usuario.',
        ],
    ],
    'rbac' => [
        'denied' => [
            'code' => 'RBAC-001',
            'userInfo' => 'No tienes permiso para realizar está acción.',
            'supportInfo' => 'Usuario autenticado sin rol, policy, gate o nivel suficiente para el recurso.',
            'developerInfo' => 'Autorizacion denegada por policy/gate/middleware. Revisar UserPolicy/SecurityAuditLogPolicy, argumentos de middleware role, estado soft-deleted del objetivo y restricciones de autoacción admin.',
        ],
        'admin_reauth_required' => [
            'code' => 'RBAC-002',
            'userInfo' => 'Reautenticación requerida.',
            'supportInfo' => 'La acción admin crítica requiere reautenticación reciente.',
            'developerInfo' => 'EnsureAdminReauthenticated redirigio porque falta admin_reauthenticated_at o tiene más de 5 minutos. El usuario debe confirmar password + TOTP en admin.reauth.store.',
        ],
        'admin_reauth_failed' => [
            'code' => 'RBAC-004',
            'userInfo' => 'Contraseña o código TOTP incorrectos.',
            'supportInfo' => 'La reautenticación admin fallo por password actual o código TOTP inválido.',
            'developerInfo' => 'ReauthController rechazo la reautenticación porque Hash::check(password) fue false o TotpService::verify(otp) regreso null. Auditoria reason=admin_reauth_failed.',
        ],
        'admin_only' => [
            'code' => 'RBAC-003',
            'userInfo' => 'No tienes permiso para realizar está acción.',
            'supportInfo' => 'Ruta visible solo para rol admin.',
            'developerInfo' => 'Middleware role:admin o policy viewAny/view denego acceso. Verificar role_id, roles.name y auth_completed_mfa_level=3 para rutas admin.',
        ],
    ],
    'validation' => [
        'invalid' => [
            'code' => 'VAL-001',
            'userInfo' => 'Datos enviados inválidos.',
            'supportInfo' => 'La validacion del Form Request fallo para uno o más campos.',
            'developerInfo' => 'La validacion Laravel fallo antes de la logica del controller. Revisar rules/messages del FormRequest, input normalizado, campos dontFlash y error bag; nunca registrar passwords, OTPs o tokens.',
        ],
        'captcha_failed' => [
            'code' => 'VAL-002',
            'userInfo' => 'No se pudo validar el formulario.',
            'supportInfo' => 'Captcha inválido, ausente o rechazado por el proveedor.',
            'developerInfo' => 'RecaptchaService::verify regreso false. Revisar recaptcha.enabled, secret key, respuesta remota, score/action si aplica, fallo de red y g-recaptcha-response enviado.',
        ],
        'username_invalid' => [
            'code' => 'VAL-003',
            'userInfo' => 'Usuario inválido.',
            'supportInfo' => 'El username no cumple el formato permitido.',
            'developerInfo' => 'Regex de username en FormRequest de login/registro fallo. Se espera username normalizado con caracteres permitidos y restricciones de longitud.',
        ],
        'password_weak' => [
            'code' => 'VAL-004',
            'userInfo' => 'La password no cumple los requisitos.',
            'supportInfo' => 'La password no cumple longitud, mayúsculas/minúsculas, números, símbolos o confirmación.',
            'developerInfo' => 'Illuminate\\Validation\\Rules\\Password fallo. Revisar longitud minima, mixedCase, números, símbolos y password_confirmation. Los valores de password están en dontFlash.',
        ],
        'email_invalid' => [
            'code' => 'VAL-005',
            'userInfo' => 'Correo inválido.',
            'supportInfo' => 'El correo no tiene formato válido o no cumple unicidad.',
            'developerInfo' => 'Validacion de email fallo. Revisar contexto nullable/required, validacion RFC, unique users.email y reglas de correo de recuperación.',
        ],
    ],
    'csrf' => [
        'failed' => [
            'code' => 'CSRF-001',
            'userInfo' => 'Sesión expirada. Intenta de nuevo.',
            'supportInfo' => 'Token CSRF inválido, ausente o asociado a una sesión expirada.',
            'developerInfo' => 'TokenMismatchException manejada por Handler. Sesión invalidada, token CSRF regenerado y cookie de sesión encolada para borrar. Revisar que forms incluyan @csrf y config SameSite/Secure.',
        ],
    ],
    'rate_limit' => [
        'blocked' => [
            'code' => 'RATE-001',
            'userInfo' => 'Demasiados intentos. Intenta más tarde.',
            'supportInfo' => 'Rate limit aplicado para proteger login, registro, MFA, recovery o acción admin.',
            'developerInfo' => 'Limiter de RouteServiceProvider regreso 429. Revisar nombre del limiter, fuente de llave hasheada (username/email/user_id/session/user_agent/ip), ventana decay, headers y security_audit_logs.metadata.limiter.',
        ],
        'login_limited' => [
            'code' => 'RATE-002',
            'userInfo' => 'Demasiados intentos. Intenta más tarde.',
            'supportInfo' => 'Rate limit especifico de login aplicado.',
            'developerInfo' => 'Limiter login: 5/min por sha512(username en minúsculas|ip). Evitar exponer si el username existe.',
        ],
        'mfa_limited' => [
            'code' => 'RATE-003',
            'userInfo' => 'Demasiados intentos. Intenta más tarde.',
            'supportInfo' => 'Rate limit especifico de MFA aplicado.',
            'developerInfo' => 'Limiter totp/webauthn/recovery-codes bloqueo solicitud por sha512(user_id o auth_pending_user_id o guest|ip). Limiters públicos deben incluir otro identificador además de IP.',
        ],
    ],
    'account' => [
        'current_password_invalid' => [
            'code' => 'ACC-001',
            'userInfo' => 'La password actual no es valida.',
            'supportInfo' => 'La confirmación de password actual fallo para una acción sensible.',
            'developerInfo' => 'Hash::check(current_password, user.password) regreso false en ProfileController::updatePassword u otro flujo sensible de cuenta. Auditar password.change_failed cuando aplique.',
        ],
        'recovery_email_missing' => [
            'code' => 'ACC-002',
            'userInfo' => 'Agrega un correo primero.',
            'supportInfo' => 'No hay correo de recuperación para enviar verificación.',
            'developerInfo' => 'ProfileController::sendEmailVerification encontro user.email vacío. El usuario debe guardar un correo de recuperación antes de enviar URL firmada de verificación.',
        ],
        'recovery_email_already_verified' => [
            'code' => 'ACC-003',
            'userInfo' => 'El correo ya está verificado.',
            'supportInfo' => 'La cuenta ya tiene email_verified_at establecido.',
            'developerInfo' => 'sendEmailVerification corto el flujo porque user.email_verified_at no es null. No debe enviarse una nueva URL firmada.',
        ],
        'email_verification_invalid' => [
            'code' => 'ACC-004',
            'userInfo' => 'No se pudo verificar el correo.',
            'supportInfo' => 'El enlace de verificación no pertenece al usuario o el hash no coincide.',
            'developerInfo' => 'ProfileController::verifyEmail fallo por propietario incorrecto o hash sha1(user.email) inválido. Validar parámetros firmados user/hash y usuario autenticado.',
        ],
        'sessions_not_available' => [
            'code' => 'ACC-005',
            'userInfo' => 'No hay sesiones para mostrar.',
            'supportInfo' => 'No hay registros de sesiones persistidas para la cuenta.',
            'developerInfo' => 'UserSessionService regreso colección vacia, normalmente porque el driver/table de sesiones en DB no tiene filas para el usuario.',
        ],
        'reauth_required' => [
            'code' => 'ACC-006',
            'userInfo' => 'Reautenticación requerida.',
            'supportInfo' => 'La acción sensible requiere reautenticación reciente.',
            'developerInfo' => 'EnsureAccountReauthenticated rechazo la solicitud porque falta account_reauthenticated_at o expiró. Confirmar password y TOTP cuando aplique.',
        ],
        'reauth_failed' => [
            'code' => 'ACC-007',
            'userInfo' => 'Contraseña o código TOTP incorrectos.',
            'supportInfo' => 'La reautenticación de cuenta fallo.',
            'developerInfo' => 'Account\\ReauthController rechazo la solicitud por Hash::check false o TotpService::verify null. No exponer que factor fallo.',
        ],
    ],
    'http' => [
        'not_found' => [
            'code' => 'HTTP-404',
            'userInfo' => 'Recurso no encontrado.',
            'supportInfo' => 'La ruta o recurso solicitado no existe o no es accesible en este estado.',
            'developerInfo' => 'HttpException 404 o abort(404). Revisar registro de ruta, route model binding, estado MFA pendiente y restricciones de propietario del recurso.',
        ],
        'method_not_allowed' => [
            'code' => 'HTTP-405',
            'userInfo' => 'Metodo no permitido.',
            'supportInfo' => 'La ruta existe pero no acepta el metodo HTTP usado.',
            'developerInfo' => 'MethodNotAllowedHttpException. Caso comun: logout debe ser POST con CSRF; GET/DELETE en rutas removidas deben regresar 405 de forma segura.',
        ],
        'unprocessable' => [
            'code' => 'HTTP-422',
            'userInfo' => 'No se pudo procesar la solicitud.',
            'supportInfo' => 'La solicitud tiene formato válido pero fallo una regla de negocio o verificación.',
            'developerInfo' => 'HTTP 422 regresado por controller/service después de validacion de dominio, por ejemplo fallo MFA/WebAuthn/password reset. Revisar código de error de dominio especifico.',
        ],
    ],
    'system' => [
        'error' => [
            'code' => 'SYS-001',
            'userInfo' => 'Error interno. Intenta más tarde.',
            'supportInfo' => 'Error inesperado sin detalles internos para usuario.',
            'developerInfo' => 'Throwable no controlado o fallo de infraestructura. Revisar clase de excepción, stack trace, request id, estado de transacción DB, dependencias queue/mail/cache y cambios recientes de deploy/config. Nunca exponer stack traces en userInfo.',
        ],
        'mail_failed' => [
            'code' => 'SYS-002',
            'userInfo' => 'No se pudo enviar el correo. Intenta más tarde.',
            'supportInfo' => 'Fallo el envío de correo transaccional.',
            'developerInfo' => 'Mail::raw/send fallo. Revisar transporte mailer, credenciales SMTP, DNS, from address, normalizacion de destinatario y logs de Laravel mail.',
        ],
        'database_failed' => [
            'code' => 'SYS-003',
            'userInfo' => 'Error interno. Intenta más tarde.',
            'supportInfo' => 'Fallo de base de datos o transacción.',
            'developerInfo' => 'Consulta/transacción de base de datos fallo. Revisar SQLSTATE, conexión pgsql, estado de migraciones, locks, constraints, deadlocks y política de reintento de transacciones.',
        ],
        'configuration_invalid' => [
            'code' => 'SYS-004',
            'userInfo' => 'Configuración no disponible. Intenta más tarde.',
            'supportInfo' => 'Configuración requerida ausente o invalida.',
            'developerInfo' => 'Configuración/env requerida ausente o inconsistente. Revisar APP_KEY, APP_URL, WEBAUTHN_RP_ID, WEBAUTHN_ORIGIN, mail, session y cache.',
        ],
    ],
];
